default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'russian_doll_development' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default

test:
  <<: *default
  database: 'russian_doll_test'

production:
  <<: *default
  database: 'russian_doll_production'
